### ISSUE TITLE
Question about SAT

### ISSUE THREAD

**Issue by bjggi** [Selindrile/SendAllTarget#3]
Hey there

I would like to switch to your Target Addon, since im still using sendtarget by DiscipleOfEris. After some testing i have two Questions:

1.) Would it be possible to shorten things for the youcommand, maybe that a command like:
//sat charactername action 
also works, so you dont have to write all the time" youcommand" when u want one of ur chars to perform an action.

2.) Now i would like to use the attackall, but without my WHM and GEO :) What would be the best approach, maybe using commandArgs in my Gearswap and then bind or macro the command like:

`elseif commandArgs[1] == 'assist' then
send_command('sat youattack Charname attack')
send_command('sat youattack Charname2 attack')
send_command('sat youattack Charname3 attack')`

or should i use schedules? Not sure about sending all commands at once?

Best regards

**Comment by Icydeath** [comment]
Just a tip: To get quicker responses, you should join his [discord channel](https://discord.gg/ug6xtvQ).

Could do something like this:
- Create a [windower script](https://docs.windower.net/commands/#command-usage) with your set of commands

In init.txt
 - add  a [alias](https://docs.windower.net/commands/alias/) and a [bind](https://docs.windower.net/commands/input/) for your newly created script

then you can just //aliasyoumade or create a macro /con AliasYouMade
or you can skip the alias/bind part and run the script directly using //exec ScriptsFileName

**Comment by bjggi** [comment]
Thanks for your replay Icydeath and no problem, im in no hurry :) (dont have discord)

I use mostly use "user_self_commands" in my Users-Globals.lua (like the code posted above) to handle such things like "all attack on maintarget" or "all debuff on maintarget", "warp2 all" etc. They work good, but...

The reason i downloaded this Addon, is because it has an "attack maintarget" function and my solution now with (simple commandAgs > assist main > attack <t>) isn't working all the time. In Dynamis D most of the time only 2/3 of my melee Chars attack. However, I hope with SendAllTarget this will be more reliable, hence the question how i should technically handle a "send command sat youattack Charname attack" to 3 of my chars. 

Since you mention Windower Scripts, is it technically faster and more reliable to use them for such things? Like sending multible commands to other Chars. Or is it basically the same as commandArgs in Gearswap? 

Atm i use Windower Scripts only for BCMN Enter, Up-Down-Enter Key Scripts etc.

Best regards

**Comment by Selindrile** [comment]
Using gearswap commands for this is, well, there's really no need to do that, inefficient for what you're trying to do, in general, you should only use gearswap commands if you need to use logic to determine the correct action, if it's just effectively typing the same thing every time, there's 0 reason to do so and it's just extra processing. You could use windower scripts, but I would recommend aliases instead as Icydeth said, they stay in memory, and can be macroed or just typed easily.

I can't easily shorten the commands because I have to split up the actions based on command names, but that said, aliases would do these jobs well, some examples.

alias assistme sat youattack bob;sat youattack sam;sat youattack billy 
-- would send attack commands to these three characters when you typed //assistme

alias billy sat youcommand billy
-- You could use the charactername as an alias for a direct command so you could type things like //billy dia
