### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BombSDiggity** [Selindrile/SendAllTarget#6]

**Comment by BombSDiggity** [comment]
Wrong button, does //sat youcommand @job work? or is there a way to go about this?

**Comment by Selindrile** [comment]
not currently, no real plans to add at the moment, sat has little in the way of use since //send incorporated most of the functionality, settarget did too, both official addons, only reason I'm leaving this up is the attack commands and the ability to make aliases that can be used regardless of action, which the others can't do
